### ISSUE TITLE
Phase locking between two lasers

### ISSUE THREAD

**Issue by ZhimingShi** [linien-org/linien#386] opened 2024-03-18 01:53 UTC
Hello！I want to use Linien to lock the phase of two lasers, can this software do that? For example, lock the laser to a frequency comb. The laser is combed with a frequency comb to obtain an RF signal less than 30MHz. The phase of the RF signal is then demodulated using Linien to obtain an error signal. The error signal is processed by PID and fed back to the laser for phase locking.

**Comment by bleykauf** [comment] 2024-04-08 13:23
Duplicate of #385.

**Closed by bleykauf** 2024-04-08 13:23 UTC
Labels: duplicate
